### ISSUE TITLE
Expose a websocket server to trigger a run, stop it, stream progression and provide the output

### ISSUE THREAD

**Issue by moreirathomas** [benchttp/engine#12]
## Description

The engine must communicate with the engine to:
- start a run on demand
- be notified the run ended with success
- be notified the run ended with error
- be notified of the run's progression
- pull the run output on demand
- stop the run on demand

WebSocket allows for this continuous and bi-directional communication. This is the suggested communication sequence flow:

![apps_conn](https://user-images.githubusercontent.com/59995859/181589761-d858f82b-79ff-47d7-9227-dc1cc1d0ff67.svg)

## Tasks

- [ ] define specs on the messages structure

## Suggestions

Suggested messages structure:

```
// desktop -> engine
ClientMessage {
  event: "run" | "stop" | "pull"
  data: Config (if "run")
}

// engine -> desktop
ServerMessage {
  event: "running" | "stopped" | "done" | "progress" | "output"
  data: Output (if "output") | Progress (if "progress")
}
```

## Dependencies

- blocks #17

**Comment by moreirathomas** [comment]
Definition the internal state of the server may help, as the process is an infinite loop between different states.

I suggest:

![conn_life_cycle](https://user-images.githubusercontent.com/59995859/181590677-6f2437e9-80e1-4be6-affd-00c86b7f96cd.svg)

My main interrogations are:
- what happens when the state is "done" or "error" and the client ask for the output?
- should it send the output (data or error) and go to "idle" state automatically?
- should it stay "done" or "error" and directly go to "running" on a run start message?
- is it the responsibility of `start()` to clear the state?

**Comment by GregoryAlbouy** [comment]
Summary of our speccing session:
- ws connection done on app init
- a run is triggered by the desktop via a ws message (a regular http call has been considered then dismissed due to increased complexity)
- during the run, the server emits a `Progress` via ws message. Desktop listen to them to refresh the progress display
- upon completion, the server emits a `Report` via ws message, communicating the result and signaling the end of the run. Desktop uses that message to display the results.

Could be for later:
- allow a single run at a time server-side
- proper error handling

Removing the `needs specs` label
